### ISSUE TITLE
Unable to install beta 3 

### ISSUE THREAD

**Issue by sshcli** [svanschu/SchuWeb-Sitemap#22] opened 2017-01-11 14:08 UTC
This error is for the package: pkg_schuweb_sitemap_3.0.0.B3_20170110

![error](https://cloud.githubusercontent.com/assets/12942731/21851477/a31e1d08-d7e5-11e6-9bcf-5769e715eb7f.PNG)

This error is for the package: com_schuweb_sitemap_3.0.0.B3_20170110
![error2](https://cloud.githubusercontent.com/assets/12942731/21851476/a319d66c-d7e5-11e6-9ff7-28d7243774bd.PNG)

**Comment by sshcli** [comment] 2017-01-12 13:00
Seems like It will also break your current installation

**Comment by svanschu** [comment] 2017-01-12 15:37
Oh that's not good. I've only done some small changes based on JEDChecker -.- damn wouldn't expect that ...

lesson learned ...

**Comment by ramonlopez23** [comment] 2017-02-16 07:41
HI! 
I have the same problem, and same result.

**Comment by svanschu** [comment] 2017-02-16 22:26
Well look into it. Hope I get next week to it.

**Comment by Sarge2013** [comment] 2017-03-25 12:48
Hello, just confirm that the problem is still here - same screenshots as above. 
Downloaded today, tried to install on PHP7, Joomla 3.6.
Watch this thread and news with great interest,

**Comment by svanschu** [comment] 2017-03-28 08:23
Sorry for the delay :( I'm in the middle of moving to a new apartment.

**Closed** 2017-06-19 21:25 UTC
Labels: bug

**Comment by Sarge2013** [comment] 2017-06-19 21:55
Hello !
You've closed the issue - may I ask - is the problem solved ?
Serge


Tuesday, June 20, 2017, 12:25:39 AM, you wrote:

Closed #22 via b4d36be.

**Comment by sshcli** [comment] 2017-06-19 22:06
@Sarge2013 I assume it's solved.
Just wait for the next release.

**Comment by svanschu** [comment] 2017-06-19 22:59
Yes it is

**Comment by Sarge2013** [comment] 2017-06-20 06:37
Thanks !
Waiting for the next release, while there are no something new at https://github.com/svanschu/SchuWeb-Sitemap/releases 
Good luck !
Serge


Tuesday, June 20, 2017, 1:06:54 AM, you wrote:

@Sarge2013 I assume it's solved.
Just wait for the next release.

**Comment by Sarge2013** [comment] 2017-06-20 09:49
FYI - checked just now, same issues with installation
Warning
JFolder::create: Could not create folder.Path: /var/www/html/alt/example.com
Warning: Failed to move file: /tmp/phpijwaIg to /var/www/html/alt/example.com/tmp/com_schuweb_sitemap_3.0.0.B3_20170110.zip
Error
Archive does not exist
Unable to find install package
Please, keep informed abt new stable releases,
Best regards
Serge


Tuesday, June 20, 2017, 1:59:42 AM, you wrote:

Yes it is

**Comment by svanschu** [comment] 2017-06-20 10:22
I don't know what you have done, but that is definitely not the same error message.
